clinicApptManagement/force-app/main/default/objects/Contact/fields/Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_ID__c</fullName>
    <displayFormat>A-{00000}</displayFormat>
    <externalId>true</externalId>
    <label>Unique ID</label>
    <type>AutoNumber</type>
</CustomField>

clinicApptManagement/force-app/main/default/objects/Contact/recordTypes/Physician.recordType-meta.xml
<RecordType>
    <fullName>Physician</fullName>
    <active>true</active>
    <label>Physician</label>
</RecordType>

clinicApptManagement/force-app/main/default/objects/NamedCredPhysician__mdt/NamedCredPhysician__mdt.object-meta.xml
<CustomObject>
    <label>NamedCredPhysician</label>
    <pluralLabel>NamedCredPhysician</pluralLabel>
</CustomObject>

clinicApptManagement/force-app/main/default/objects/NamedCredPhysician__mdt/fields/Physician_Number__c.field-meta.xml
<CustomField>
    <fullName>Physician_Number__c</fullName>
    <label>Physician Number</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

clinicApptManagement/force-app/main/default/classes/fetchGoogleInviteDaily.cls
public without sharing class fetchGoogleInviteDaily implements schedulable{
    ID phyId;
    public fetchGoogleInviteDaily(Id physicianId){
        if(String.isNotBlank(physicianId)){
            this.phyId = physicianId;
        }
    }
    public void execute(SchedulableContext sc){
        Contact physician = [SELECT ID,Unique_ID__c FROM Contact WHERE Id =:phyId ];
        List<NamedCredPhysician__mdt> nmCreds = [SELECT ID,Label FROM NamedCredPhysician__mdt WHERE Physician_Number__c =: physician.Unique_ID__c LIMIT 1];
        if(nmCreds.size()>0 && nmCreds[0].Label !=null){
            GoogleEventFetchSvc.fetchEvents(nmCreds[0].Label,physician.id);
        }
		
    }
}