clinicApptManagement/force-app/main/default/objects/Account/fields/Appointment_Price__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Price__c</fullName>
    <label>Appointment Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

clinicApptManagement/force-app/main/default/objects/Account/recordTypes/Department.recordType-meta.xml
<RecordType>
    <fullName>Department</fullName>
    <active>true</active>
    <label>Department</label>
</RecordType>

clinicApptManagement/force-app/main/default/objects/Contact/fields/Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_ID__c</fullName>
    <displayFormat>A-{00000}</displayFormat>
    <externalId>true</externalId>
    <label>Unique ID</label>
    <type>AutoNumber</type>
</CustomField>

clinicApptManagement/force-app/main/default/objects/Contact/recordTypes/Patient.recordType-meta.xml
<RecordType>
    <fullName>Patient</fullName>
    <active>true</active>
    <label>Patient</label>
</RecordType>

clinicApptManagement/force-app/main/default/objects/Contact/recordTypes/Physician.recordType-meta.xml
<RecordType>
    <fullName>Physician</fullName>
    <active>true</active>
    <label>Physician</label>
</RecordType>

clinicApptManagement/force-app/main/default/objects/Department_Physician__c/Department_Physician__c.object-meta.xml
<CustomObject>
    <label>Department Physician</label>
    <nameField>
        <displayFormat>DP-{0000}</displayFormat>
        <label>Department Physician</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Physicians</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

clinicApptManagement/force-app/main/default/objects/Department_Physician__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Department</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Department Physicians</relationshipLabel>
    <relationshipName>Department_Physicians</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

clinicApptManagement/force-app/main/default/objects/Department_Physician__c/fields/Physician__c.field-meta.xml
<CustomField>
    <fullName>Physician__c</fullName>
    <label>Physician</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Department Physicians</relationshipLabel>
    <relationshipName>Department_Physicians</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

clinicApptManagement/force-app/main/default/objects/Patient_Appointment__c/Patient_Appointment__c.object-meta.xml
<CustomObject>
    <label>Patient Appointment</label>
    <nameField>
        <displayFormat>APT-{0000}</displayFormat>
        <label>Appointment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

clinicApptManagement/force-app/main/default/objects/Patient_Appointment__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Department</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient Appointments</relationshipLabel>
    <relationshipName>Patient_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

clinicApptManagement/force-app/main/default/objects/Patient_Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Patient Appointments</relationshipLabel>
    <relationshipName>Patient_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

clinicApptManagement/force-app/main/default/objects/Patient_Appointment__c/fields/Physician__c.field-meta.xml
<CustomField>
    <fullName>Physician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Physician</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Physician</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Patient Appointments (Physician)</relationshipLabel>
    <relationshipName>Patient_Appointments1</relationshipName>
    <type>Lookup</type>
</CustomField>

clinicApptManagement/force-app/main/default/objects/Patient_Appointment__c/fields/Reason_for_Cancelling_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Cancelling_Appointment__c</fullName>
    <label>Reason for Cancelling Appointment</label>
    <type>TextArea</type>
</CustomField>

clinicApptManagement/force-app/main/default/objects/Patient_Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

clinicApptManagement/force-app/main/default/objects/Patient_Appointment__c/fields/Time_Slot__c.field-meta.xml
<CustomField>
    <fullName>Time_Slot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Time Slot</label>
    <referenceTo>Time_Slot__c</referenceTo>
    <relationshipLabel>Patient Appointments</relationshipLabel>
    <relationshipName>Patient_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

clinicApptManagement/force-app/main/default/objects/Time_Slot__c/Time_Slot__c.object-meta.xml
<CustomObject>
    <label>Time Slot</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

clinicApptManagement/force-app/main/default/objects/Time_Slot__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Department</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Time Slots</relationshipLabel>
    <relationshipName>Time_Slots</relationshipName>
    <type>Lookup</type>
</CustomField>

clinicApptManagement/force-app/main/default/objects/Time_Slot__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning</fullName>
            </value>
            <value>
                <fullName>Afternoon</fullName>
            </value>
            <value>
                <fullName>Evening</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

clinicApptManagement/force-app/main/default/classes/ClinicManagementTestClass.cls
@isTest
private class ClinicManagementTestClass {
    @testSetup
    private static void setup(){
        
        List<String> specialization = new List<String>();
        specialization.add('Cardiology');
        specialization.add('Endocrinology');
        specialization.add('Rheumatology');
        specialization.add('General Practice');
        List<Account> accounts = new List<Account>();
        id recTypDeptId = Schema.sObjectType.Account.getRecordTypeInfosByDeveloperName().get('Department').getRecordTypeId();
        for(String spec : specialization){
            accounts.add(new Account(Name = spec,Appointment_Price__c = 100,recordTypeId=recTypDeptId));
        }
        insert accounts;
        
        Contact patient = new Contact();
        patient.LastName = 'Patient';
        patient.FirstName = 'Test';
        patient.Email = 'test@test.com.invalid';
        patient.RecordTypeId = Schema.sObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Patient').getRecordTypeId();
        insert patient;
        
        Contact physician = new Contact();
        physician.LastName = 'Physician';
        physician.FirstName = 'Test';
        physician.Email = 'physician@test.com.invalid';
        physician.AccountId = accounts[0].Id;
        physician.RecordTypeId = Schema.sObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Physician').getRecordTypeId();
        insert physician;
        List<Department_Physician__c> deptPhys = new List<Department_Physician__c>();
        List<Time_Slot__c> timeSlots = new List<Time_Slot__c>();
        for(Account a : accounts){
            Department_Physician__c deptPhy = new Department_Physician__c();
            deptPhy.Physician__c = physician.Id;
            deptPhy.Department__c = a.Id;
            deptPhys.add(deptPhy);
            
            Time_Slot__c ts = new Time_Slot__c();
            ts.Time__c = Time.newInstance(8, 0, 0, 0);
            ts.Type__c = 'Morning';
            ts.Department__c = a.Id;
            
            Time_Slot__c ts1 = new Time_Slot__c();
            ts1.Time__c = Time.newInstance(9, 0, 0, 0);
            ts1.Type__c = 'Morning';
            ts1.Department__c = a.Id;
            timeSlots.add(ts);
            timeSlots.add(ts1);
        }
        insert deptPhys;
        insert timeSlots;
        
    }
    @isTest
    private static void testgetDepartment(){
        List<Account> accs = AppointmentManagerController.getDepartment();
    }
    @isTest
    private static void testcreateAppointment(){
        Account cardio = [SELECT ID FROM Account WHERE Name = 'Cardiology' LIMIT 1];
        Contact patient = [SELECT ID FROM Contact WHERE RecordType.Name='Patient' LIMIT 1];
        Contact physician = [SELECT ID FROM Contact WHERE RecordType.Name='Physician' LIMIT 1];
        Date aptDate = System.today().addDays(1);
        String aptTime = '08:00';
        Test.setMock(HttpCalloutMock.class, new GoogleCreateEventMock());
        Id aptId = AppointmentManagerController.createAppointment(String.ValueOf(cardio.Id), String.ValueOf(patient.Id), String.ValueOf(physician.Id), aptDate, aptTime);
        AppointmentManagerController.getTimeSlot(String.ValueOf(cardio.Id), 'Morning', aptDate);
        AppointmentManagerController.getAvailablePhysician('08:00', aptDate, String.ValueOf(cardio.Id));
        AppointmentManagerController.getPatientRecord(aptId);
        
        
    }
    @isTest
    private static void testgetAvailablePhysician(){
        Account cardio = [SELECT ID FROM Account WHERE Name = 'Cardiology' LIMIT 1];
        Date aptDate = System.today().addDays(1);
        String aptTime = '08:00';
        AppointmentManagerController.getAvailablePhysician(aptTime, aptDate, String.ValueOf(cardio.Id));
    }
    @isTest
    private static void testEventUtil(){
        Account cardio = [SELECT ID FROM Account WHERE Name = 'Cardiology' LIMIT 1];
        Contact patient = [SELECT ID FROM Contact WHERE RecordType.Name='Patient' LIMIT 1];
        Contact physician = [SELECT ID FROM Contact WHERE RecordType.Name='Physician' LIMIT 1];
        
        Patient_Appointment__c pApt = new Patient_Appointment__c();
        pApt.Status__c = 'Scheduled';
        pApt.Patient__c = patient.Id;
        pApt.Physician__c = physician.Id;
        insert pApt;
        Event evt = new Event();
        evt.Subject='Testing...';
        evt.Appointment_Number__c = pApt.Id;
        evt.StartDateTime = System.now();
        evt.DurationInMinutes = 30;
        evt.Google_Event_Id__c = 'ABCD';
        insert evt;
        Test.setMock(HttpCalloutMock.class, new GoogleDeleteEventMock());
        pApt.Status__c = 'Cancelled';
        pApt.Reason_for_Cancelling_Appointment__c = 'Testing...';
        update pApt;
        pApt.Status__c = 'Scheduled';
        try{
        	update pApt;    
        }
        catch(exception ex){
            System.debug(ex.getMessage());
        }
        
    }
    @isTest
    private static void testGoogleEventFetchSvc(){
        Test.startTest();
        Contact physician = [SELECT ID,Unique_Id__c FROM Contact WHERE RecordType.Name='Physician' LIMIT 1];
        Test.setMock(HttpCalloutMock.class, new GoogelEventFetchMock());
        fetchGoogleInviteDaily cls = new fetchGoogleInviteDaily(physician.id);
        System.schedule('Testing Job', '0 0 0/1 1/1 * ? *', cls);
        Test.stopTest();
    }
    
}